### ISSUE TITLE
No module named flufl.lock

### ISSUE THREAD

**Issue by uzair789** [cvlab-epfl/tf-lift#10]
WHen I try to run the command, ' main.py --task=train --subtask=desc' I get the following error.

  File "/home/uzair/tensorflow/tf-lift/datasets/eccv2016/eccv.py", line 55, in <module>
    from flufl.lock import Lock
ImportError: No module named flufl.lock

I tried to install this package but that is leading to more errors. How do I install this package? should I do it with pip? Does the lift code base require any particular version of python like python3 or python3.4?

**Comment by kmyi** [comment]
Please pip install flufl.lock
Both Python3 and Python2.7 should be fine
