### ISSUE TITLE
Descriptor position

### ISSUE THREAD

**Issue by luczeng** [cvlab-epfl/tf-lift#19]
Dear all,

I have run the whole test pipeline on one image (kp, ori, desc). To my surprise, it seems that the number of descriptor doesn't match that of the keypoints.
Therefore my question is : which descriptor vector goes with which keypoint location ?

For example, I extract the keypoints info using the following : 

`kp_list = loadKpListFromTxt(keypointFile)`

And I extract the descriptors from the h5 file  as follow :

```
f = h5py.File(descriptorFile, 'r')
a_group_key = list(f.keys())[0]
descriptors = list(f[a_group_key])
```
To which element in kp_list does descriptors[i] correspond to ?

**Comment by kmyi** [comment]
The keypoints that cause out-of-bounds support regions are discarded. I believe that the descriptor file also has the keypoints included to avoid confusion.

**Comment by FangGet** [comment]
Extracted kps' number at step 1 and kps' saved in h5 file is not the same, as descriptor calculation step will filter out some unsuitable kps. So in h5 file, kps and descriptors are saved simultanous, and its number must be the same.

**Comment by luczeng** [comment]
> To which element in kp_list does descriptors[i] correspond to ?

Ok, thank you very much. Indeed the keypoints are also included in the h5 file.

**Comment by chuanzhidong** [comment]
> > To which element in kp_list does descriptors[i] correspond to ?
> 
> Ok, thank you very much. Indeed the keypoints are also included in the h5 file.

@TheToadAlly Can you share the codes how to use the descriptor.h5 file to do keypoint matching? Thank you very much.

**Comment by Shu-HowTing** [comment]
> > To which element in kp_list does descriptors[i] correspond to ?
> 
> Ok, thank you very much. Indeed the keypoints are also included in the h5 file.

@TheToadAlly Can you share the codes how to use the descriptor.h5 file to do keypoint matching? Thank you very much.
