### ISSUE TITLE
Lift features not uint8

### ISSUE THREAD

**Issue by luczeng** [cvlab-epfl/tf-lift#20]
Dear all,

I am surprised to see that the LIFT features are not uint8 but float.

This is quite surprising as SIFT is usually of uint8 type. I understand that they are not between 0-255, as some normalization has probably been applied before training. 

However, I am usually using uint8 features. Will I lose precision by converting LIFT features to uint8 ?

Thanks

**Comment by kmyi** [comment]
SIFT features are actually float, but the openCV implementation just quantizes it after scaling I believe. Simple conversion to uint8 would be problematic, but doing something similar, i.e. quantizing after scaling to a proper range should not drastically affect performance. However, of course this leaves a lot of room for user error.
