### ISSUE TITLE
Runtime error while testing

### ISSUE THREAD

**Issue by tv12345** [cvlab-epfl/tf-lift#21]
Hello, 

I am getting the following error every time i am trying to run one of the command in testing:-

python main.py --task=test --subtask=ori --logdir=logs/test --test_img_file=image1.jpg --test_out_file=image1_ori.txt --test_kp_file=image1_kp.txt --use_batch_norm=False
/home/user/anaconda2/envs/tf/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
User and hostname: user@8RM7KY3
2018-07-06 18:54:33.866125: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
-- Using default values for mean/std
---------
Variables: name (type shape) [size]
---------
network/lift/ori/conv-act-pool-1/weights:0 (float32_ref 5x5x1x10) [250, bytes: 1000]
network/lift/ori/conv-act-pool-1/biases:0 (float32_ref 10) [10, bytes: 40]
network/lift/ori/conv-act-pool-2/weights:0 (float32_ref 5x5x10x20) [5000, bytes: 20000]
network/lift/ori/conv-act-pool-2/biases:0 (float32_ref 20) [20, bytes: 80]
network/lift/ori/conv-act-pool-3/weights:0 (float32_ref 3x3x20x50) [9000, bytes: 36000]
network/lift/ori/conv-act-pool-3/biases:0 (float32_ref 50) [50, bytes: 200]
network/lift/ori/fc-ghh-drop-4/weights:0 (float32_ref 1250x1600) [2000000, bytes: 8000000]
network/lift/ori/fc-ghh-drop-4/biases:0 (float32_ref 1600) [1600, bytes: 6400]
network/lift/ori/fc-ghh-5/weights:0 (float32_ref 100x32) [3200, bytes: 12800]
network/lift/ori/fc-ghh-5/biases:0 (float32_ref 32) [32, bytes: 128]
network/lift/desc/conv-act-pool-norm-1/weights:0 (float32_ref 7x7x1x32) [1568, bytes: 6272]
network/lift/desc/conv-act-pool-norm-1/biases:0 (float32_ref 32) [32, bytes: 128]
network/lift/desc/conv-act-pool-norm-2/weights:0 (float32_ref 6x6x32x64) [73728, bytes: 294912]
network/lift/desc/conv-act-pool-norm-2/biases:0 (float32_ref 64) [64, bytes: 256]
network/lift/desc/conv-act-pool-3/weights:0 (float32_ref 5x5x64x128) [204800, bytes: 819200]
network/lift/desc/conv-act-pool-3/biases:0 (float32_ref 128) [128, bytes: 512]
Total size of variables: 2299482
Total bytes of variables: 9197928
-------------------------------------------------
 Loading Trained Network 
-------------------------------------------------
[joint] Checking if old pre-trained weights exists in 
[joint] No pretrained weights from the old framework
[joint] Checking if previous Tensorflow run exists in 
[joint] No previous Tensorflow result
[joint] Checking if previous Tensorflow run exists in logs/test/joint
[joint] No previous Tensorflow result
[ori] Checking if old pre-trained weights exists in 
[ori] No pretrained weights from the old framework
[ori] Checking if previous Tensorflow run exists in 
[ori] No previous Tensorflow result
[ori] Checking if previous Tensorflow run exists in logs/test/ori
[ori] No previous Tensorflow result
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/user/anaconda2/envs/tf/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 70, in main
    task.run()
  File "/media/user/SSD-0/Linux/Projects/TF_LIFT/tf-lift-master/tester.py", line 110, in run
    raise RuntimeError("Could not load network weights!")
RuntimeError: Could not load network weights!

I am using Tensorflor 1.4, Cuda 8, opencv3.4. tensorboard 0.4. Any suggestions to resolve this error, will be very helpful.

Thanks in advance.

**Comment by kmyi** [comment]
Hi,

it's telling you that it cannot load weights? So probably you want to check if the paths are correct?

Cheers

**Comment by tv12345** [comment]
I am running the command where main.py is located. The command for testing, i am trying is :- 
python main.py --task=test --subtask=kp --logdir=logs/test --test_img_file=image1.jpg \
  --test_out_file=image1_kp.txt

**Comment by kmyi** [comment]
You probably want to remove the try catch surrounding the `restore_network` and see why the restoration is failing.

**Comment by qiuweibo** [comment]
Hi, I have exactly the same problem here. 

I am confused about "remove the try catch surrounding the restore_network" ? I have deleted all 
_pycache_ and try again. Still it has the same problem.

The path of main.py and image1.jpg are all correct. Could you please help with this problem? Thanks so much.

**Comment by miraclewxl** [comment]
I have same problem with you. I even create some file folders such as log. But the problem still exist

**Comment by kmyi** [comment]
Hi Guys, I'm traveling at the moment. You can debug this your selves by removing the 

https://github.com/cvlab-epfl/tf-lift/blob/5530e47dcbb13f1d5642477834c8105c26957f25/tester.py#L103

try except here and then diving into where the crash exactly happened.

**Comment by kmyi** [comment]
Closed due to no further activity
