### ISSUE TITLE
scales-histogram-minsc-2

### ISSUE THREAD

**Issue by JanDempewolf** [cvlab-epfl/tf-lift#25]
When I run: main.py --task=train --subtask=desc

I get this error : OSError: Unable to open file (Unable to open file: name = '/users/test/datasets/eccv/piccadilly/scales-histogram-minsc-2.0.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

Does any one know why that is?

**Comment by kmyi** [comment]
We are not providing the training dataset for now. That's what that error message is saying.
