### ISSUE TITLE
Reproduce images matching of your publication

### ISSUE THREAD

**Issue by MBocchi** [cvlab-epfl/tf-lift#30]
Hi, I saw your publication about the matching keypoints/descriptors of skull's image. The result are impressive and I would like to reproduce it, but I am not able to do it.

I have converted the keypoints list of both images to **OpenCV** format thanks to the **`kp_list_2_opencv_kp_list()`** function, but I don't know how to match the descriptors. Does the descriptors are compatible with **OpenCV** format to use **`cv2.BFMatcher().match(desc1, desc2)`** ?
Or maybe you used antoher way to match images...

Thank you!

**Comment by kmyi** [comment]
We simply use nearest neighbor matching, I think the BFMatcher does the same probably.... However, you can probably just code that part yourself easily.
