### ISSUE TITLE
Professor,thank you for sharing your codes!Here are my questions:

### ISSUE THREAD

**Issue by Shu-HowTing** [cvlab-epfl/tf-lift#32]
I download the model you provide in the end.(`Models without rotation augmentation`)and put them in the 
folder`log/test` .Then ,I run the following commad:
`python main.py --task=test --subtask=kp --logdir=logs/test --test_img_file=1.jpg --test_out_file=image1_kp.txt `
The error like this:`At least two variables have the same name: network/lift/kp/conv-ghh-1/biases`

**I want to know whether the model  match the code!and what is meaning of**
> run with --use_batch_norm=False --mean_std_type=dataset 

Looking for your answer!

**Comment by Shu-HowTing** [comment]
Professor,thank you for sharing your codes!Here are my questions: 
I downaled the

**Comment by 4xle** [comment]
Version of tensorflow too new. Downgrade to 1.4.

**Comment by Shu-HowTing** [comment]
Thank you for your reply! Should I add the`--use_batch_norm=False --mean_std_type=dataset`to the command`python main.py --task=test --subtask=kp ····`

**Comment by kmyi** [comment]
Please downgrade to TF 1.4
