### ISSUE TITLE
position

### ISSUE THREAD

**Issue by Shu-HowTing** [cvlab-epfl/tf-lift#33]

**Comment by Shu-HowTing** [comment]
Sir,I got the 13 dimensions vectors of each keypoints. I just want to  know which two dimensions corresponds to the coordinate of the keypoints?

**Comment by kmyi** [comment]
Please see

https://github.com/cvlab-epfl/tf-lift/blob/8990e2286425c4d58c0107931729ee3d0a250313/utils/kp_tools.py#L42

**Comment by Shu-HowTing** [comment]
I got it! thank you,professor!




On 12/2/2018 23:35，Kwang Moo Yi<notifications@github.com> wrote：

Please see

https://github.com/cvlab-epfl/tf-lift/blob/8990e2286425c4d58c0107931729ee3d0a250313/utils/kp_tools.py#L42
