### ISSUE TITLE
missing scales-histogram-minsc-2.0.h5 

### ISSUE THREAD

**Issue by Jimmymiji** [cvlab-epfl/tf-lift#37]
Hi, I try to run the command python main.py --task=main --subtask=desc.  
But it always produces the error saying that can not open file scales-histogram-minsc-2.0.h5, which does not exist in any of the folders. May I know where to download the dataset?  
Sorry for bothering with this naive problem. Thank you very much!

**Comment by kmyi** [comment]
Hi,

Please see issue #28 for details!

Thanks,
Kwang

**Comment by JiangHai0929** [comment]
Hi，have you solved this problem?I also meet the same problem
