### ISSUE TITLE
train the netWork

### ISSUE THREAD

**Issue by Actmaiji** [cvlab-epfl/tf-lift#4]
Do I need to use visualSFM the reconstruct the image in 3D?
Or all I do is just to down load the  image "Piccadilly
Circus in London and the Roman Forum in Rome from [29]" to train the network?
I mean what should I do to prepare  the datasets ?

thanks for your attention.

**Comment by kmyi** [comment]
You would need to construct the SfM models yourself.
As of now, we do not provide any training data.
Please see the paper for details on how this is done.

Kwang

**Comment by Actmaiji** [comment]
Thanks,I will  try my best to do it.
best wishes

Maiji
