### ISSUE TITLE
How to visualize the train loss and accuracy curve while training?

### ISSUE THREAD

**Issue by punisher220** [cvlab-epfl/tf-lift#44]
Hello,I have finished training pre-processing code and got the training available for desc, ori and kp subtasks.

But in utils/dump.py I noticed that you only did best_validation loss and iteration step(also with std.h5 and mean.h5) record in the training result. 
 
I am new to the tensorflow model code. I wonder: Are there any approaches to make the train loss and accuracy(If available) for visualization.
Thanks for help.

**Comment by kmyi** [comment]
Shouldn't it dump those to tensorboard? I am not 100% sure since I've not touched this code for so long, but I usually dump them there
