### ISSUE TITLE
What is the latest development of LIFT? Is it being under improvement?

### ISSUE THREAD

**Issue by nvip12041994** [cvlab-epfl/tf-lift#45]
Dear Professor, 

I am currently a master student learning computer vision as my main field and I have recently read your paper released in 2016 about Learned Invariant Feature Transform (LIFT). After reading through the whole paper, I was really impressed with the idea and also the performance of LIFT when it could drastically beat other traditional detectors in terms of accuracy. However, it is quite a surprise to me that I do not see the development of it today meaning it is not included in image processing libraries such as open CV and people are also not discussing its potential anymore. 
For that reason, may you please give me some insights about what are the weaknesses and difficulty of this method stopping it from developing today?
I would love to hear your response soon! 

Thanks and best regards!
Phuong

**Comment by etrulls** [comment]
This method is five years old and has not been under development for a long time. You can check our more recent local feature papers and their citations if you want to see where the state of the art is/is going.
