### ISSUE TITLE
Activation for DESC is 'relu' rather than 'Tanh' in config.py by default

### ISSUE THREAD

**Issue by ZeroSteven618** [cvlab-epfl/tf-lift#47]
Excuse me, I have a question for the LIFT network implementation. 
I found the supplementary description of your LIFT paper as:
![LIFT_Structure](https://user-images.githubusercontent.com/66064813/98760239-d2846980-240d-11eb-99dd-bcd5e8c9bd5f.png)

In the picture you set the **Activation for DESC** part as **Tanh**. However:
I noticed that in your config.py you set **config.desc_activ** as **'relu'** as default setting.
Then in your **modules/lift_desc.py**, from Line 69 to Line 75 the **activation for DESC** part will set to ''relu" if I run the python scripts as default setting. 

Is it a wrong setting in the code? Or the activation of **relu** or **Tanh** does not matter so much in **DESC** part?
Or did I miss some setting changes in another place?

**Comment by etrulls** [comment]
You are correct, that's what we originally did [here](https://github.com/cvlab-epfl/LIFT), with Theano (and before that, [here](https://github.com/etrulls/deepdesc-release), with luatorch), but when porting to tensorflow ReLU performed either the same or slightly better, so this current repository uses ReLU. You can try it yourself with `--desc_activ`.

**Comment by ZeroSteven618** [comment]
Thanks for your reply!
