### ISSUE TITLE
I wonder a question: why LIFT performs so better than SIFT?

### ISSUE THREAD

**Issue by ZeroSteven618** [cvlab-epfl/tf-lift#49]
Excuse me, I am sorry to bother you with the theoretical question.

During the LIFT pipeline, you got 4 patches based on VSFM, which is the patches samples label tool. 
The VSFM performs reconstruction with SIFT. 

I an not sure about: Why the SIFT based training data can work so better than SIFT? Also better than the state-of-the-art methods.

Is it from the **score map** in KP part network?

**Comment by kmyi** [comment]
Multiple things. But in a nutshell, since the network learns which points are best statistically from large data.
