### ISSUE TITLE
Unable to open file scales-histogram-minsc-2.0.h5

### ISSUE THREAD

**Issue by zimizile** [cvlab-epfl/tf-lift#5]
![image](https://user-images.githubusercontent.com/8552112/32707717-d69a7ba6-c860-11e7-84bf-e1b47772f81f.png)
Unable to open file scales-histogram-minsc-2.0.h5，I have search，there is no file scales-histogram-minsc-2.0.h5 in the datasets.
Whats wrong?

**Comment by etrulls** [comment]
Try 'pip install tqdm'.

**Comment by etrulls** [comment]
I see you updated the issue. As I mentioned in the e-mail, you have to format the datasets. We do not provide instructions for this but you can look at the code to see how it works.

**Comment by zimizile** [comment]
Which code I need to see to format the datasets?

**Comment by kmyi** [comment]
Look at how the dataset related code is treated.

**Comment by zimizile** [comment]
OK.I know.
I will see the code. Thanks a lot.
