### ISSUE TITLE
I have get split-60-20-20-train-minsc-2.0.h.txt,please close the issue

### ISSUE THREAD

**Issue by zimizile** [cvlab-epfl/tf-lift#6]
I have get the file split-60-20-20-train-minsc-2.0.h.txt .
This issue can close...

**Comment by zimizile** [comment]
I have fixed this problem.Use this code in eccv.py
scale_hist = scale_hist/np.sum(scale_hist)
But now,I find another problem.
![image](https://user-images.githubusercontent.com/8552112/33114286-1efbd556-cf97-11e7-923b-f4eeda2d2242.png)
How can I get the file    split-60-20-20-train-minsc-2.0.h.txt    ?

**Comment by punisher220** [comment]
Excuse me, @zimizile 
I have been stuck in LIFT training dataset construction. Have you solved the problem of generating all required data for LIFT training?
Can I discuss it with you? Thank you.

**Comment by punisher220** [comment]
Hello, @zimizile I am sorry to bother you. 
I have got the img-kp-minsc-2.0.h5 files for each jpg file with valid_keypoints and other_keypoints data 
with my own code for reading the files from VisualSFM.
Then I have got the scales-histogram-2.0.h5 file with the help of the helper.py. 

However then I met the problem:
TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

I wonder how did you solve the problem. Could you please give me some hints(to get the split-60-20-20-train-minsc-2.0.h.txt and the split-60-20-20-train-minsc-2.0.h5 files)?
