### ISSUE TITLE
Unable to open file:split-60-20 -20-minsc-2.0.h5

### ISSUE THREAD

**Issue by zimizile** [cvlab-epfl/tf-lift#7]
For this time,I dont know how to fix it.Help me please.
Unable to open file:split-60-20 -20-minsc-2.0.h5
I can get scales-histogram-minsc-2.0.h5,but I dont konw how to get split-60-20 -20-minsc-2.0.h5.
![image](https://user-images.githubusercontent.com/8552112/33117600-fdc5b3b8-cfa3-11e7-8034-7320e7c039bf.png)

**Comment by kmyi** [comment]
Hi,

Please avoid spamming the issue tracker. As of now, we do *not* provide any packaged training data. Also, the code is very self-explanatory, so please try to understand the code first.

I will close the issue.

Cheers,
Kwang

**Comment by zimizile** [comment]
Ok.I know.Thanks a lot.I will not open new issue.
