### ISSUE TITLE
How to download data?

### ISSUE THREAD

**Issue by XudongLinthu** [cvlab-epfl/tf-lift#9]
Hi, guys,
Could someone tell me where to download the required dataset (Piccadily?) and or something else to get the codes running?
Thanks,
Xudong

**Comment by etrulls** [comment]
Hi,

I think you can find the raw images here, among other places:
http://www.cs.cornell.edu/projects/1dsfm/

We don't provide the formatted data, as we expect people to use their own
datasets. In our case, we require an SfM reconstruction, i.e. surviving
keypoints and match data, and a list of keypoints not surviving the SfM
reconstruction, which are not used for training but are necessary to mine
non-keypoint areas. Besides that, there are smaller details such as a
histogram of keypoint scales which are easy to generate. You can look into
datasets/eccv2016.py, it's relatively straightforward to understand.

Best,
E.

**Comment by hurricane2018** [comment]
It's hard to understand

**Comment by kmyi** [comment]
Hi, I'll close this issue tracker now.
